spring:
  application:
    name: crypto-investment
  datasource:
    url: jdbc:h2:mem:cryptodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
server:
  port: 8080
rate:
  limit:
    per:
      window: 10
    time:
      window: 60000